language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install mysql-python"
# command to run tests
script: nosetests tests
services: mysql